fix: Use debian stretch image instead of slim-stertch
slim だと diesel を含めたらコンパイルできなくなった。

```
error: linking with `cc` failed: exit code: 1

note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L"
"/usr/local/..."
```

slim じゃない stretch だと大丈夫そう。